on:
  push:
    branches:
      - '**'

jobs:
  build-macosx:
    name: Build for MacOSX
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v1
      - name: Test formula
        run: |
          brew install --verbose --debug ./Formula/vasmm68k.rb
          brew test
