on:
  push:
    branches:
      - '**'

jobs:
  build-macosx:
    name: Build for MacOSX
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v1
      - name: Install formula
        run: brew install --verbose --debug ./Formula/vasmm68k.rb
      - name: Test formula
        run: brew test vasmm68k
